# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:    
          fetch-depth: 0
          filter: tree:0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build
        shell: pwsh
        run: ./release.ps1    
        env:
          NUGET_API_KEY_CONSOLO_CI: ${{ secrets.NUGET_API_KEY_CONSOLO_CI }}
